### ISSUE TITLE
Discrepancy in TileDB version between recipe and `conda_build_config.yaml`

### ISSUE THREAD

**Issue by jdblischak** [conda-forge/tiledb-py-feedstock#153]
I'm confused by the purpose of specifying a TileDB version in `recipe/conda_build_config.yaml`. It is set to `2.10`, while the recipe is set to `2.11.*`. If the value in `recipe/conda_build_config.yaml` is being ignored, can it just be deleted for the sake of clarity?

https://github.com/conda-forge/tiledb-py-feedstock/blob/dd1d3b27be79a07fe85dfc4b379fe99cdba09cb1/recipe/conda_build_config.yaml#L9-L10

https://github.com/conda-forge/tiledb-py-feedstock/blob/dd1d3b27be79a07fe85dfc4b379fe99cdba09cb1/recipe/meta.yaml#L35

https://github.com/conda-forge/tiledb-py-feedstock/blob/dd1d3b27be79a07fe85dfc4b379fe99cdba09cb1/recipe/meta.yaml#L42

**Comment by ihnorton** [comment]
Fixed by https://github.com/conda-forge/tiledb-py-feedstock/pull/152

At some point we needed to temporarily reverse a pin which had already been merged globally in conda-forge-pinning. Despite reducing the pin version in `recipe/meta.yaml`, I think I was still seeing the rendered CI scripts with the global pin version, so I added the pin in `conda_build_config.yaml`. But I may have misunderstood whether that took precedence over the version in `recipe/meta.yaml`.

**Comment by jdblischak** [comment]
Thanks for the quick fix!

> But I may have misunderstood whether that took precedence over the version in recipe/meta.yaml.

I'm not quite sure how `meta.yaml` and `conda_build_config.yaml` are behaving in this instance, or what the expected behavior should be. As can be seen in the [rerendering commit](https://github.com/conda-forge/tiledb-py-feedstock/commit/94b774907231f2161a71b31f5d8a14ca5a205f10), the tiledb pinning to 2.10 had been propagated to all of CI helper files, but it appears that at least recently the `meta.yaml` pinning took precendence.
